---
#tasks file for docker_compose_zabbix
- name: "—Åreate directory"
  file:
    path: "{{folder}}"
    state: "directory"

- name: "copy file"
  copy:
    src: "{{src}}"
    dest: "{{dest}}"

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{folder}}"
  register: output

- name: print home_dirs variable
  ansible.builtin.debug:
    var: output