version: "3"
services:
  zabbix-db:
    image: postgres:15.1
    container_name: zabbix-db
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: zabbix
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      zabbix-monitoring:
        ipv4_address: 172.22.0.2
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4:8.3
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: bsresh@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: <password>
    ports:
      - 8080:80
    networks:
      zabbix-monitoring:
        ipv4_address: 172.22.0.3
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:6.2.6-alpine
    links:
      - zabbix-db
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: 172.22.0.2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <password>
    ports:
      - 10051:10051
    networks:
      zabbix-monitoring:
        ipv4_address: 172.22.0.4
    restart: always


  zabbix-agent:
    image: zabbix/zabbix-agent:6.2.6-alpine
    links:
      - zabbix-server
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: 172.22.0.4
    networks:
      zabbix-monitoring:
        ipv4_address: 172.22.0.6
    restart: always

  zabbix_wgui:
    image: zabbix/zabbix-web-nginx-pgsql:6.2.6-alpine
    links:
      - zabbix-db
      - zabbix-server
    container_name: zabbix-frontend
    environment:
      ZBX_SERVER_HOST: 172.22.0.4
      ZBX_SERVER_PORT: 10051
      DB_SERVER_HOST: 172.22.0.2
      DB_SERVER_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: zabbix
      ZBX_SERVER_NAME: monitoring
      PHP_TZ: Europe/Moscow
    ports:
      - 80:8080
      - 443:8443
    networks:
      zabbix-monitoring:
        ipv4_address: 172.22.0.5
    restart: always

networks:
  zabbix-monitoring:
    driver: bridge
    ipam:
      config:
      - subnet: 172.22.0.0/24
