version: '3.8'
  
services:
  kibana:
    image: kibana:7.16.2
    container_name: kibana
    volumes:
      - ./configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    restart: always

networks:
  elk:
    driver: bridge
