---
- name: install docker and docker compose
  hosts: 
    - zabbix
    - elasticsearch
    - kibana
  gather_facts: no
  become: yes
  roles: 
    - name: install_docker

- name: zabbix-agent
  hosts:
    - bastion
    - webservers
    - kibana
    - elasticsearch
  gather_facts: yes
  become: yes
  roles:
    - role: community.zabbix.zabbix_agent
      zabbix_agent_version: 6.2
      zabbix_agent_server: zabbix.ru-central1.internal

- name: zabbix-agent for zabbix-server
  hosts:
    - zabbix
  gather_facts: yes
  become: yes
  roles:
    - role: community.zabbix.zabbix_agent
      zabbix_agent_version: 6.2
      zabbix_agent_server: 172.22.0.3

- name: firewall zabbix agent
  hosts:
  - webservers
  gather_facts: no
  become: yes
  tasks:
    - name: firewall zabbix agent
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 10050
        jump: ACCEPT
    - name: Save current state of the firewall in system file
      community.general.iptables_state:
        state: saved
        path: /etc/iptables/rules.v4

- name: docker-compose zabbix
  hosts:
    - zabbix
  gather_facts: no
  become: yes
  roles: 
    - name: docker_compose_zabbix

- name: copy site
  hosts: 
   - webservers
  gather_facts: no
  become: yes
  tags:
  - copy_site
  roles: 
    - name: copy_site_content
      html_dir: /var/www/html/
      src: sibtur-travel.ru.zip

- name: nginx configuration
  hosts:
   - webservers
  gather_facts: no
  become: yes
  roles:
    - name: nginx_config
  
- name: install filebeat
  hosts: 
  - webservers
  gather_facts: yes
  become: yes
  roles: 
    - name: install_filebeat

- name: docker-compose elasticsearch
  hosts:
  - elasticsearch
  gather_facts: no
  become: yes
  roles: 
    - name: docker_compose_elasticsearch

- name: docker-compose kibana
  hosts:
   - kibana
  gather_facts: no
  become: yes
  roles: 
    - name: docker_compose_kibana
